steps:
  ####################
  # api
  ####################
  - name: 'gcr.io/cloud-builders/docker' # Docker Build
    args: ['build', 
           '-t', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-api:$SHORT_SHA', 
           '-t', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-api:latest', 
           '--cache-from',
           'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-api:latest', 
           'node-3tier-app2/api']
  - name: 'gcr.io/cloud-builders/docker' # Docker Push
    args: ['push', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-api', '--all-tags']
  ####################
  # web
  ####################
  - name: 'gcr.io/cloud-builders/docker' # Docker Build
    args: ['build', 
           '-t', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-web:$SHORT_SHA', 
           '-t', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-web:latest', 
           '--cache-from',
           'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-web:latest', 
           'node-3tier-app2/web']
  - name: 'gcr.io/cloud-builders/docker' # Docker Push
    args: ['push', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/poptal-docker/app2-web', '--all-tags']