steps:
  # Docker Build
  # - name: 'gcr.io/cloud-builders/docker'
    # args: ['build', '-t', 
           # 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/toptal-docker/app2-api', 'node-3tier-app2/api']
  # - name: 'gcr.io/cloud-builders/docker'
    # args: ['push', 'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/toptal-docker/app2-api']

  - name: 'gcr.io/$PROJECT_ID/helm'
    args: ['ls ', '-al']
    # args: ['upgrade', '-n', 'app2', '-f', './node-3tier-app2/heml_charts/app2-api/values.yaml', 'app2-api', './node-3tier-app2/heml_charts/app2-api']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast2-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-toptal'
