steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'northamerica-northeast2-docker.pkg.dev/silicon-pointer-146802/toptal-docker/app2-api', 
           'api']

